version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "jgarber623"
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/google/cloud-functions/transform-image"
    schedule:
      interval: "monthly"
    assignees:
      - "jgarber623"
