---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
    - "**.erb"
    - "**.rb"
  exclude_paths:
    - "config/**/*"
