dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.4.2
before_install:
  - gem update --system
  - gem update bundler
script:
  - bundle exec rubocop
notifications:
  email: false
  slack: sixtwothree:yATLmjTW15443qR7jbCWr3RO
