name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec bundle-audit check --update
  build:
    name: Build
    needs: [audit, lint, test]
    if: github.ref_name == 'production'
    runs-on: ubuntu-latest
    environment:
      REPOSITORY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - uses: docker/metadata-action@v3
        id: docker-meta
        with:
          flavor: |
            latest=true
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
          target: production
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rubocop
      - run: bundle exec reek
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |-
          sudo apt update
          sudo apt install libvips
      - name: Run RSpec
        run: bundle exec rspec --format RSpec::Github::Formatter
      - uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
